/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/komari-knowledge/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge */
        get: operations["list_knowledge_api_komari_knowledge_v1_knowledge_get"];
        put?: never;
        /** Create Knowledge */
        post: operations["create_knowledge_api_komari_knowledge_v1_knowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-knowledge/v1/knowledge/{kid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge */
        get: operations["get_knowledge_api_komari_knowledge_v1_knowledge__kid__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge */
        delete: operations["delete_knowledge_api_komari_knowledge_v1_knowledge__kid__delete"];
        options?: never;
        head?: never;
        /** Update Knowledge */
        patch: operations["update_knowledge_api_komari_knowledge_v1_knowledge__kid__patch"];
        trace?: never;
    };
    "/api/komari-knowledge/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Knowledge */
        post: operations["search_knowledge_api_komari_knowledge_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-help/v1/help": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Help */
        get: operations["list_help_api_komari_help_v1_help_get"];
        put?: never;
        /** Create Help */
        post: operations["create_help_api_komari_help_v1_help_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-help/v1/help/{hid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Help */
        get: operations["get_help_api_komari_help_v1_help__hid__get"];
        put?: never;
        post?: never;
        /** Delete Help */
        delete: operations["delete_help_api_komari_help_v1_help__hid__delete"];
        options?: never;
        head?: never;
        /** Update Help */
        patch: operations["update_help_api_komari_help_v1_help__hid__patch"];
        trace?: never;
    };
    "/api/komari-help/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Help */
        post: operations["search_help_api_komari_help_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-help/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Help */
        post: operations["scan_help_api_komari_help_v1_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_komari_memory_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_komari_memory_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_komari_memory_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_komari_memory_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Update Conversation */
        patch: operations["update_conversation_api_komari_memory_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/komari-memory/v1/user-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Profiles */
        get: operations["list_user_profiles_api_komari_memory_v1_user_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/user-profiles/{group_id}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Profile */
        get: operations["get_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__get"];
        /** Put User Profile */
        put: operations["put_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__put"];
        post?: never;
        /** Delete User Profile */
        delete: operations["delete_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/interaction-histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interaction Histories */
        get: operations["list_interaction_histories_api_komari_memory_v1_interaction_histories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/interaction-histories/{group_id}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interaction History */
        get: operations["get_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__get"];
        /** Put Interaction History */
        put: operations["put_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__put"];
        post?: never;
        /** Delete Interaction History */
        delete: operations["delete_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-provider/v1/reply-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reply Logs */
        get: operations["list_reply_logs_api_llm_provider_v1_reply_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-provider/v1/reply-logs/{date}/{line_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reply Log */
        get: operations["get_reply_log_api_llm_provider_v1_reply_logs__date___line_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-management-config/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Config Resources */
        get: operations["list_config_resources_api_komari_management_config_v1_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-management-config/v1/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config Resource */
        get: operations["get_config_resource_api_komari_management_config_v1_resources__resource_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-management-config/v1/resources/{resource_id}/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload Config Resource */
        post: operations["reload_config_resource_api_komari_management_config_v1_resources__resource_id__reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-management-config/v1/resources/{resource_id}/fields/{field_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Config Field */
        patch: operations["update_config_field_api_komari_management_config_v1_resources__resource_id__fields__field_name__patch"];
        trace?: never;
    };
    "/api/komari-management-prompt/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompt Resources */
        get: operations["list_prompt_resources_api_komari_management_prompt_v1_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-management-prompt/v1/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt Resource */
        get: operations["get_prompt_resource_api_komari_management_prompt_v1_resources__resource_id__get"];
        /** Replace Prompt Resource */
        put: operations["replace_prompt_resource_api_komari_management_prompt_v1_resources__resource_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-management-prompt/v1/resources/{resource_id}/fields/{field_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Prompt Field */
        patch: operations["update_prompt_field_api_komari_management_prompt_v1_resources__resource_id__fields__field_name__patch"];
        trace?: never;
    };
    "/api/komari-announce/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Groups
         * @description 获取 Bot 已加入的群列表。
         */
        get: operations["list_groups_api_komari_announce_v1_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-announce/v1/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Maintenance Announce
         * @description 向指定群发送维护通知。
         */
        post: operations["send_maintenance_announce_api_komari_announce_v1_maintenance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnounceResult
         * @description 单个群发送结果。
         */
        AnnounceResult: {
            /** Group Id */
            group_id: number;
            /** Success */
            success: boolean;
            /** Error */
            error?: string | null;
        };
        /**
         * ConfigFieldUpdateRequest
         * @description 配置字段更新请求。
         */
        ConfigFieldUpdateRequest: {
            /**
             * Value
             * @description 新的字段值
             */
            value: unknown;
        };
        /**
         * ConfigResourceDetail
         * @description 配置资源详情。
         */
        ConfigResourceDetail: {
            /** Resource Id */
            resource_id: string;
            /** Display Name */
            display_name: string;
            /** Config File */
            config_file: string;
            /** Fields */
            fields: string[];
            /** Field Descriptions */
            field_descriptions: {
                [key: string]: string;
            };
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /**
         * ConfigResourceListResponse
         * @description 配置资源列表响应。
         */
        ConfigResourceListResponse: {
            /** Items */
            items: components["schemas"]["ConfigResourceSummary"][];
            /** Total */
            total: number;
        };
        /**
         * ConfigResourceSummary
         * @description 配置资源摘要。
         */
        ConfigResourceSummary: {
            /** Resource Id */
            resource_id: string;
            /** Display Name */
            display_name: string;
            /** Config File */
            config_file: string;
            /** Fields */
            fields: string[];
            /** Field Descriptions */
            field_descriptions: {
                [key: string]: string;
            };
        };
        /**
         * ConversationCreateRequest
         * @description 创建对话记忆请求。
         */
        ConversationCreateRequest: {
            /** Group Id */
            group_id: string;
            /** Summary */
            summary: string;
            /** Participants */
            participants?: string[];
            /**
             * Importance Initial
             * @default 3
             */
            importance_initial: number;
            /** Importance Current */
            importance_current?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Last Accessed */
            last_accessed?: string | null;
        };
        /**
         * ConversationEntry
         * @description 对话记忆条目。
         */
        ConversationEntry: {
            /** Id */
            id: number;
            /** Group Id */
            group_id: string;
            /** Summary */
            summary: string;
            /** Participants */
            participants?: string[];
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Importance Initial */
            importance_initial: number;
            /** Importance Current */
            importance_current: number;
            /** Last Accessed */
            last_accessed?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ConversationListResponse
         * @description 对话记忆列表响应。
         */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ConversationUpdateRequest
         * @description 更新对话记忆请求。
         */
        ConversationUpdateRequest: {
            /** Group Id */
            group_id?: string | null;
            /** Summary */
            summary?: string | null;
            /** Participants */
            participants?: string[] | null;
            /** Importance Initial */
            importance_initial?: number | null;
            /** Importance Current */
            importance_current?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Last Accessed */
            last_accessed?: string | null;
        };
        /**
         * GroupInfo
         * @description 群信息摘要。
         */
        GroupInfo: {
            /** Group Id */
            group_id: number;
            /** Group Name */
            group_name: string;
            /** Member Count */
            member_count: number;
        };
        /**
         * GroupListResponse
         * @description 群列表响应。
         */
        GroupListResponse: {
            /** Groups */
            groups: components["schemas"]["GroupInfo"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HelpCreateRequest
         * @description 新增帮助条目请求。
         */
        HelpCreateRequest: {
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Keywords */
            keywords?: string[];
            /**
             * Category
             * @default other
             * @enum {string}
             */
            category: "command" | "feature" | "faq" | "other";
            /** Plugin Name */
            plugin_name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * HelpEntry
         * @description 帮助文档单条记录。
         */
        HelpEntry: {
            /** Id */
            id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "command" | "feature" | "faq" | "other";
            /** Plugin Name */
            plugin_name?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Notes */
            notes?: string | null;
            /**
             * Is Auto Generated
             * @default false
             */
            is_auto_generated: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * HelpListResponse
         * @description 帮助条目列表响应。
         */
        HelpListResponse: {
            /** Items */
            items: components["schemas"]["HelpEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * HelpScanResponse
         * @description 扫描结果响应。
         */
        HelpScanResponse: {
            /** Updated Count */
            updated_count: number;
        };
        /**
         * HelpSearchRequest
         * @description 帮助检索请求。
         */
        HelpSearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /**
         * HelpSearchResult
         * @description 帮助检索结果。
         */
        HelpSearchResult: {
            /** Id */
            id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "command" | "feature" | "faq" | "other";
            /** Plugin Name */
            plugin_name?: string | null;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Similarity
             * @default 0
             */
            similarity: number;
            /**
             * Source
             * @default keyword
             * @enum {string}
             */
            source: "keyword" | "vector";
        };
        /**
         * HelpUpdateRequest
         * @description 更新帮助条目请求。
         */
        HelpUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Category */
            category?: ("command" | "feature" | "faq" | "other") | null;
            /** Plugin Name */
            plugin_name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * KnowledgeCreateRequest
         * @description 新增知识请求。
         */
        KnowledgeCreateRequest: {
            /** Content */
            content: string;
            /** Keywords */
            keywords: string[];
            /**
             * Category
             * @default general
             * @enum {string}
             */
            category: "general" | "character" | "setting" | "plot" | "other";
            /** Notes */
            notes?: string | null;
        };
        /**
         * KnowledgeEntry
         * @description 知识库单条记录。
         */
        KnowledgeEntry: {
            /** Id */
            id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "general" | "character" | "setting" | "plot" | "other";
            /** Keywords */
            keywords?: string[];
            /** Content */
            content: string;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * KnowledgeListResponse
         * @description 知识列表响应。
         */
        KnowledgeListResponse: {
            /** Items */
            items: components["schemas"]["KnowledgeEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * KnowledgeSearchHit
         * @description 检索结果。
         */
        KnowledgeSearchHit: {
            /** Id */
            id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "general" | "character" | "setting" | "plot" | "other";
            /** Content */
            content: string;
            /**
             * Similarity
             * @default 0
             */
            similarity: number;
            /**
             * Source
             * @default keyword
             * @enum {string}
             */
            source: "keyword" | "vector";
        };
        /**
         * KnowledgeSearchRequest
         * @description 检索测试请求。
         */
        KnowledgeSearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /**
         * KnowledgeUpdateRequest
         * @description 更新知识请求。
         */
        KnowledgeUpdateRequest: {
            /** Content */
            content?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Category */
            category?: ("general" | "character" | "setting" | "plot" | "other") | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * MaintenanceAnnounceRequest
         * @description 维护通知发送请求。
         */
        MaintenanceAnnounceRequest: {
            /**
             * Title
             * @description 维护标题
             */
            title: string;
            /**
             * Content
             * @description 维护内容，多行文本，每行一条
             */
            content: string;
            /**
             * Scheduled Time
             * @description 预定维护时间
             */
            scheduled_time: string;
            /**
             * Group Ids
             * @description 目标群号列表
             */
            group_ids: number[];
        };
        /**
         * MaintenanceAnnounceResponse
         * @description 维护通知发送结果。
         */
        MaintenanceAnnounceResponse: {
            /** Results */
            results: components["schemas"]["AnnounceResult"][];
            /** Total */
            total: number;
            /** Success Count */
            success_count: number;
            /** Failed Count */
            failed_count: number;
        };
        /**
         * MemoryEntityEntry
         * @description 实体文档条目。
         */
        MemoryEntityEntry: {
            /** User Id */
            user_id: string;
            /** Group Id */
            group_id: string;
            /** Key */
            key: string;
            /** Category */
            category: string;
            /** Importance */
            importance: number;
            /** Access Count */
            access_count: number;
            /** Last Accessed */
            last_accessed?: string | null;
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /**
         * MemoryEntityListResponse
         * @description 实体文档列表响应。
         */
        MemoryEntityListResponse: {
            /** Items */
            items: components["schemas"]["MemoryEntityEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PromptFieldUpdateRequest
         * @description 提示词字段更新请求。
         */
        PromptFieldUpdateRequest: {
            /**
             * Value
             * @description 新的提示词内容
             */
            value: string;
        };
        /**
         * PromptResourceDetail
         * @description 提示词资源详情。
         */
        PromptResourceDetail: {
            /** Resource Id */
            resource_id: string;
            /** Display Name */
            display_name: string;
            /** File Path */
            file_path: string;
            /** Fields */
            fields: string[];
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * PromptResourceListResponse
         * @description 提示词资源列表响应。
         */
        PromptResourceListResponse: {
            /** Items */
            items: components["schemas"]["PromptResourceSummary"][];
            /** Total */
            total: number;
        };
        /**
         * PromptResourceSummary
         * @description 提示词资源摘要。
         */
        PromptResourceSummary: {
            /** Resource Id */
            resource_id: string;
            /** Display Name */
            display_name: string;
            /** File Path */
            file_path: string;
            /** Fields */
            fields: string[];
        };
        /**
         * ReplyLogDetail
         * @description reply 日志详情。
         */
        ReplyLogDetail: {
            /** Date */
            date: string;
            /** Line Number */
            line_number: number;
            /** Timestamp */
            timestamp: string;
            /** Method */
            method: string;
            /** Model */
            model: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /**
             * Phase
             * @default
             */
            phase: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /**
             * Input Preview
             * @default
             */
            input_preview: string;
            /**
             * Output Preview
             * @default
             */
            output_preview: string;
            /**
             * Error Preview
             * @default
             */
            error_preview: string;
            /** Input */
            input?: unknown;
            /** Output */
            output?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ReplyLogListItem
         * @description reply 日志摘要。
         */
        ReplyLogListItem: {
            /** Date */
            date: string;
            /** Line Number */
            line_number: number;
            /** Timestamp */
            timestamp: string;
            /** Method */
            method: string;
            /** Model */
            model: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /**
             * Phase
             * @default
             */
            phase: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /**
             * Input Preview
             * @default
             */
            input_preview: string;
            /**
             * Output Preview
             * @default
             */
            output_preview: string;
            /**
             * Error Preview
             * @default
             */
            error_preview: string;
        };
        /**
         * ReplyLogListResponse
         * @description reply 日志列表响应。
         */
        ReplyLogListResponse: {
            /** Items */
            items: components["schemas"]["ReplyLogListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_knowledge_api_komari_knowledge_v1_knowledge_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: ("general" | "character" | "setting" | "plot" | "other") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_api_komari_knowledge_v1_knowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_api_komari_knowledge_v1_knowledge__kid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_api_komari_knowledge_v1_knowledge__kid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_knowledge_api_komari_knowledge_v1_knowledge__kid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_api_komari_knowledge_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_help_api_komari_help_v1_help_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: ("command" | "feature" | "faq" | "other") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_help_api_komari_help_v1_help_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HelpCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_help_api_komari_help_v1_help__hid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_help_api_komari_help_v1_help__hid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_help_api_komari_help_v1_help__hid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HelpUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_help_api_komari_help_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HelpSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_help_api_komari_help_v1_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpScanResponse"];
                };
            };
        };
    };
    list_conversations_api_komari_memory_v1_conversations_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                participant?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_komari_memory_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_komari_memory_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_komari_memory_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_komari_memory_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_profiles_api_komari_memory_v1_user_profiles_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                user_id?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__put: {
        parameters: {
            query?: {
                importance?: number;
            };
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interaction_histories_api_komari_memory_v1_interaction_histories_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                user_id?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__put: {
        parameters: {
            query?: {
                importance?: number;
            };
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reply_logs_api_llm_provider_v1_reply_logs_get: {
        parameters: {
            query?: {
                date?: string | null;
                days?: number;
                trace_id?: string | null;
                model?: string | null;
                method?: string | null;
                status?: ("success" | "error") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reply_log_api_llm_provider_v1_reply_logs__date___line_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                line_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyLogDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_config_resources_api_komari_management_config_v1_resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResourceListResponse"];
                };
            };
        };
    };
    get_config_resource_api_komari_management_config_v1_resources__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reload_config_resource_api_komari_management_config_v1_resources__resource_id__reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_config_field_api_komari_management_config_v1_resources__resource_id__fields__field_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
                field_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigFieldUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompt_resources_api_komari_management_prompt_v1_resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResourceListResponse"];
                };
            };
        };
    };
    get_prompt_resource_api_komari_management_prompt_v1_resources__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_prompt_resource_api_komari_management_prompt_v1_resources__resource_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_prompt_field_api_komari_management_prompt_v1_resources__resource_id__fields__field_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: string;
                field_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptFieldUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_komari_announce_v1_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListResponse"];
                };
            };
        };
    };
    send_maintenance_announce_api_komari_announce_v1_maintenance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceAnnounceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceAnnounceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
