/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/komari-knowledge/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge */
        get: operations["list_knowledge_api_komari_knowledge_v1_knowledge_get"];
        put?: never;
        /** Create Knowledge */
        post: operations["create_knowledge_api_komari_knowledge_v1_knowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-knowledge/v1/knowledge/{kid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge */
        get: operations["get_knowledge_api_komari_knowledge_v1_knowledge__kid__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge */
        delete: operations["delete_knowledge_api_komari_knowledge_v1_knowledge__kid__delete"];
        options?: never;
        head?: never;
        /** Update Knowledge */
        patch: operations["update_knowledge_api_komari_knowledge_v1_knowledge__kid__patch"];
        trace?: never;
    };
    "/api/komari-knowledge/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Knowledge */
        post: operations["search_knowledge_api_komari_knowledge_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_komari_memory_v1_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_komari_memory_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_komari_memory_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_komari_memory_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Update Conversation */
        patch: operations["update_conversation_api_komari_memory_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/komari-memory/v1/user-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Profiles */
        get: operations["list_user_profiles_api_komari_memory_v1_user_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/user-profiles/{group_id}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Profile */
        get: operations["get_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__get"];
        /** Put User Profile */
        put: operations["put_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__put"];
        post?: never;
        /** Delete User Profile */
        delete: operations["delete_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/interaction-histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interaction Histories */
        get: operations["list_interaction_histories_api_komari_memory_v1_interaction_histories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/komari-memory/v1/interaction-histories/{group_id}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interaction History */
        get: operations["get_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__get"];
        /** Put Interaction History */
        put: operations["put_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__put"];
        post?: never;
        /** Delete Interaction History */
        delete: operations["delete_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-provider/v1/reply-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reply Logs */
        get: operations["list_reply_logs_api_llm_provider_v1_reply_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-provider/v1/reply-logs/{date}/{line_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reply Log */
        get: operations["get_reply_log_api_llm_provider_v1_reply_logs__date___line_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConversationCreateRequest
         * @description 创建对话记忆请求。
         */
        ConversationCreateRequest: {
            /** Group Id */
            group_id: string;
            /** Summary */
            summary: string;
            /** Participants */
            participants?: string[];
            /**
             * Importance Initial
             * @default 3
             */
            importance_initial: number;
            /** Importance Current */
            importance_current?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Last Accessed */
            last_accessed?: string | null;
        };
        /**
         * ConversationEntry
         * @description 对话记忆条目。
         */
        ConversationEntry: {
            /** Id */
            id: number;
            /** Group Id */
            group_id: string;
            /** Summary */
            summary: string;
            /** Participants */
            participants?: string[];
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Importance Initial */
            importance_initial: number;
            /** Importance Current */
            importance_current: number;
            /** Last Accessed */
            last_accessed?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ConversationListResponse
         * @description 对话记忆列表响应。
         */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ConversationUpdateRequest
         * @description 更新对话记忆请求。
         */
        ConversationUpdateRequest: {
            /** Group Id */
            group_id?: string | null;
            /** Summary */
            summary?: string | null;
            /** Participants */
            participants?: string[] | null;
            /** Importance Initial */
            importance_initial?: number | null;
            /** Importance Current */
            importance_current?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Last Accessed */
            last_accessed?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KnowledgeCreateRequest
         * @description 新增知识请求。
         */
        KnowledgeCreateRequest: {
            /** Content */
            content: string;
            /** Keywords */
            keywords: string[];
            /**
             * Category
             * @default general
             * @enum {string}
             */
            category: "general" | "character" | "setting" | "plot" | "other";
            /** Notes */
            notes?: string | null;
        };
        /**
         * KnowledgeEntry
         * @description 知识库单条记录。
         */
        KnowledgeEntry: {
            /** Id */
            id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "general" | "character" | "setting" | "plot" | "other";
            /** Keywords */
            keywords?: string[];
            /** Content */
            content: string;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * KnowledgeListResponse
         * @description 知识列表响应。
         */
        KnowledgeListResponse: {
            /** Items */
            items: components["schemas"]["KnowledgeEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * KnowledgeSearchHit
         * @description 检索结果。
         */
        KnowledgeSearchHit: {
            /** Id */
            id: number;
            /**
             * Category
             * @enum {string}
             */
            category: "general" | "character" | "setting" | "plot" | "other";
            /** Content */
            content: string;
            /**
             * Similarity
             * @default 0
             */
            similarity: number;
            /**
             * Source
             * @default keyword
             * @enum {string}
             */
            source: "keyword" | "vector";
        };
        /**
         * KnowledgeSearchRequest
         * @description 检索测试请求。
         */
        KnowledgeSearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 5
             */
            limit: number;
        };
        /**
         * KnowledgeUpdateRequest
         * @description 更新知识请求。
         */
        KnowledgeUpdateRequest: {
            /** Content */
            content?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Category */
            category?: ("general" | "character" | "setting" | "plot" | "other") | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * MemoryEntityEntry
         * @description 实体文档条目。
         */
        MemoryEntityEntry: {
            /** User Id */
            user_id: string;
            /** Group Id */
            group_id: string;
            /** Key */
            key: string;
            /** Category */
            category: string;
            /** Importance */
            importance: number;
            /** Access Count */
            access_count: number;
            /** Last Accessed */
            last_accessed?: string | null;
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /**
         * MemoryEntityListResponse
         * @description 实体文档列表响应。
         */
        MemoryEntityListResponse: {
            /** Items */
            items: components["schemas"]["MemoryEntityEntry"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ReplyLogDetail
         * @description reply 日志详情。
         */
        ReplyLogDetail: {
            /** Date */
            date: string;
            /** Line Number */
            line_number: number;
            /** Timestamp */
            timestamp: string;
            /** Method */
            method: string;
            /** Model */
            model: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /**
             * Phase
             * @default
             */
            phase: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /**
             * Input Preview
             * @default
             */
            input_preview: string;
            /**
             * Output Preview
             * @default
             */
            output_preview: string;
            /**
             * Error Preview
             * @default
             */
            error_preview: string;
            /** Input */
            input?: unknown;
            /** Output */
            output?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ReplyLogListItem
         * @description reply 日志摘要。
         */
        ReplyLogListItem: {
            /** Date */
            date: string;
            /** Line Number */
            line_number: number;
            /** Timestamp */
            timestamp: string;
            /** Method */
            method: string;
            /** Model */
            model: string;
            /**
             * Trace Id
             * @default
             */
            trace_id: string;
            /**
             * Phase
             * @default
             */
            phase: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /**
             * Input Preview
             * @default
             */
            input_preview: string;
            /**
             * Output Preview
             * @default
             */
            output_preview: string;
            /**
             * Error Preview
             * @default
             */
            error_preview: string;
        };
        /**
         * ReplyLogListResponse
         * @description reply 日志列表响应。
         */
        ReplyLogListResponse: {
            /** Items */
            items: components["schemas"]["ReplyLogListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_knowledge_api_komari_knowledge_v1_knowledge_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: ("general" | "character" | "setting" | "plot" | "other") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_api_komari_knowledge_v1_knowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_api_komari_knowledge_v1_knowledge__kid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_api_komari_knowledge_v1_knowledge__kid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_knowledge_api_komari_knowledge_v1_knowledge__kid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_api_komari_knowledge_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_komari_memory_v1_conversations_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                participant?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_komari_memory_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_komari_memory_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_komari_memory_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_komari_memory_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_profiles_api_komari_memory_v1_user_profiles_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                user_id?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__put: {
        parameters: {
            query?: {
                importance?: number;
            };
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_profile_api_komari_memory_v1_user_profiles__group_id___user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interaction_histories_api_komari_memory_v1_interaction_histories_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                user_id?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__put: {
        parameters: {
            query?: {
                importance?: number;
            };
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntityEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interaction_history_api_komari_memory_v1_interaction_histories__group_id___user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reply_logs_api_llm_provider_v1_reply_logs_get: {
        parameters: {
            query?: {
                date?: string | null;
                days?: number;
                trace_id?: string | null;
                model?: string | null;
                method?: string | null;
                status?: ("success" | "error") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reply_log_api_llm_provider_v1_reply_logs__date___line_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                line_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyLogDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
